# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: node_registry.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'node_registry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13node_registry.proto\x12\x0cnoderegistry\"\x07\n\x05\x45mpty\";\n\x0fRegisterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"\x1a\n\nGetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"U\n\rUpdateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\x04host\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04port\x18\x03 \x01(\x05H\x01\x88\x01\x01\x42\x07\n\x05_hostB\x07\n\x05_port\"\x1d\n\rDeleteRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"|\n\x0cNodeResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04host\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x12\n\nupdated_at\x18\x07 \x01(\t\"5\n\x08NodeList\x12)\n\x05nodes\x18\x01 \x03(\x0b\x32\x1a.noderegistry.NodeResponse\"A\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\n\n\x02\x64\x62\x18\x02 \x01(\t\x12\x13\n\x0bnodes_count\x18\x03 \x01(\x05\x32\x83\x03\n\x0cNodeRegistry\x12\x45\n\x08Register\x12\x1d.noderegistry.RegisterRequest\x1a\x1a.noderegistry.NodeResponse\x12\x33\n\x04List\x12\x13.noderegistry.Empty\x1a\x16.noderegistry.NodeList\x12;\n\x03Get\x12\x18.noderegistry.GetRequest\x1a\x1a.noderegistry.NodeResponse\x12\x41\n\x06Update\x12\x1b.noderegistry.UpdateRequest\x1a\x1a.noderegistry.NodeResponse\x12:\n\x06\x44\x65lete\x12\x1b.noderegistry.DeleteRequest\x1a\x13.noderegistry.Empty\x12;\n\x06Health\x12\x13.noderegistry.Empty\x1a\x1c.noderegistry.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_registry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=37
  _globals['_EMPTY']._serialized_end=44
  _globals['_REGISTERREQUEST']._serialized_start=46
  _globals['_REGISTERREQUEST']._serialized_end=105
  _globals['_GETREQUEST']._serialized_start=107
  _globals['_GETREQUEST']._serialized_end=133
  _globals['_UPDATEREQUEST']._serialized_start=135
  _globals['_UPDATEREQUEST']._serialized_end=220
  _globals['_DELETEREQUEST']._serialized_start=222
  _globals['_DELETEREQUEST']._serialized_end=251
  _globals['_NODERESPONSE']._serialized_start=253
  _globals['_NODERESPONSE']._serialized_end=377
  _globals['_NODELIST']._serialized_start=379
  _globals['_NODELIST']._serialized_end=432
  _globals['_HEALTHRESPONSE']._serialized_start=434
  _globals['_HEALTHRESPONSE']._serialized_end=499
  _globals['_NODEREGISTRY']._serialized_start=502
  _globals['_NODEREGISTRY']._serialized_end=889
# @@protoc_insertion_point(module_scope)
